# NO-OP placeholder that always passes for other paths
# This is here so that we're able to set the status check as required

name: Microsite Void
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/verify_microsite.yml'
      - 'microsite/**'
      - 'beps/**'
      - 'mkdocs.yml'
      - 'docs/**'

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest

    name: Microsite
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - run: echo NOOP
